### ISSUE TITLE
README example does not work

### ISSUE THREAD

**Issue by mgcrea** [AOEpeople/puppeteer-fetchbot#2]
Not sure what is wrong but I can't make a simple example to work:

```js
import FetchBot from 'fetchbot';

const fetchbot = new FetchBot('', {
  attached: false,
  slowmo: 250,
  width: 1280,
  height: 1024,
  trust: true
});

// Pass a path to a job configuration file
(async () => {
  const fetchBotData = await fetchbot.runAndStandby(`${__dirname}/templates/test.json`);
  console.dir(fetchBotData);
})();
```

Only gives me an empty object output: `{}`

- `test.json`

```
{
  "https://google.com": {
    "root": true,
    "type": [["input[type=\"text\"]", "puppeteer-fetchbot aoepeople"], ["input[type=\"text\"]", "\n"]]
  },
  "/search": {
    "fetch": {
      "h3.r > a AS headlines": [],
      "h3.r > a AS links": {
        "attr": "href",
        "type": []
      }
    },
    "waitFor": [[1000]]
  }
}
```

Any ideas?

--- 

*update*: the hacker-news.json update does work so I guess there might be an issue with this one. Might be worth changing the example in the readme as it is the first thing people will try.

**Comment by BernhardBehrendt** [comment]
Hey @mgcrea,

thanks for well documented issue — helped me a lot to fix quickly :-)
Seems markup has changed so the example won't work anymore.

When modifying your test.json and remove `[type=\"text\"]` on both type commands it's working again.

Can you confirm?

Here the test.json content:

```json
{
  "https://google.com": {
    "root": true,
    "type": [["input", "puppeteer-fetchbot aoepeople"], ["input", "\n"]]
  },
  "/search": {
    "fetch": {
      "h3.r > a AS headlines": [],
      "h3.r > a AS links": {
        "attr": "href",
        "type": []
      }
    },
    "waitFor": [[1000]]
  }
}
``` 

Once it's working for you I'll push an updated example.
